@startuml
title Scaling

:round robin;
  fork
	:Task 1;
	:Task 3;
  fork again
	:Task 2;
	:Task 4;
  end fork
end


:smallest mailbox;
  fork
	:Task 1;
	:Task 3;
	:Task 4;
  fork again
	:Task 2;
	:Task 5;
  end fork
end


:scatter gather;
  fork
	:Task 1;
  fork again
	:Task 1;
  end fork
end




:consistent hashing;
  fork
	:customer a;
    :customer c;
    :customer a;
  fork again
	:customer b;
    :customer d;
    :customer d;
  end fork
end



@enduml
